# 1) Implement Perceptron training algorithm to classify flowers in IRIS dataset.

In [7]:
# Importing Packages
import matplotlib.pyplot as plt
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets
from sklearn.metrics import accuracy_score, confusion_matrix  # Add this line

In [8]:
# Fetching data from the Iris Dataset
data=datasets.load_iris()
print(data)
x=data.data
y=data.target
z=data.target_names
print(data.feature_names)
print(x[0])

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [9]:
# Buliding model and Spliting the data into Train and Test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.5)
print(x_train.shape)
print(x_test.shape)
model = Sequential()
model.add(Dense(100,input_dim=(4),activation="relu"))
model.add(Dense(3,activation="softmax"))
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])
model.fit(x_train,y_train,epochs=20)
model.evaluate(x_test,y_test)
pred = model.predict(x_test[:10])
print(pred)
p=np.argmax(pred,axis=1)
print(p)
print(y_test[:10])
for i in p:
  print("Predicted class : {} , Name : {}".format(i,x[i]))

(75, 4)
(75, 4)
Epoch 1/20
3/3 [==============================] - 0s 5ms/step - loss: 1.1807 - accuracy: 0.3067
Epoch 2/20
3/3 [==============================] - 0s 4ms/step - loss: 1.0719 - accuracy: 0.3067
Epoch 3/20
3/3 [==============================] - 0s 4ms/step - loss: 1.0162 - accuracy: 0.3067
Epoch 4/20
3/3 [==============================] - 0s 4ms/step - loss: 0.9762 - accuracy: 0.6533
Epoch 5/20
3/3 [==============================] - 0s 4ms/step - loss: 0.9452 - accuracy: 0.6933
Epoch 6/20
3/3 [==============================] - 0s 4ms/step - loss: 0.9164 - accuracy: 0.6933
Epoch 7/20
3/3 [==============================] - 0s 4ms/step - loss: 0.8854 - accuracy: 0.6933
Epoch 8/20
3/3 [==============================] - 0s 4ms/step - loss: 0.8557 - accuracy: 0.7067
Epoch 9/20
3/3 [==============================] - 0s 5ms/step - loss: 0.8317 - accuracy: 0.8400
Epoch 10/20
3/3 [==============================] - 0s 4ms/step - loss: 0.8116 - accuracy: 0.7067
Epoch 11/20
3/3 [======

In [10]:
# Evaluate the model on the test set
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')

3/3 [==============================] - 0s 3ms/step - loss: 0.6294 - accuracy: 0.7067
Test Loss: 0.6294, Test Accuracy: 0.7067


In [11]:
# Making Predictions using the model
pred = model.predict(x_test)
y_pred = np.argmax(pred, axis=1)

3/3 [==============================] - 0s 3ms/step


In [12]:
# Calculate accuracy
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.7067


In [13]:
# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

Confusion Matrix:
[[25  0  0]
 [ 0 23  0]
 [ 0 22  5]]
